
# Deconvolution

## SVR

``` {r eval = TRUE}

deconvolution <- function(exp.mat, sig.mat, ncores) {
  
  merge.mat <- list(y = as.matrix(exp.mat[rownames(sig.mat), ]), x = as.matrix(sig.mat) )
  nu <- c(0.25, 0.5, 0.75, 1)

  res <- parallel::mclapply(seq_len(ncol(merge.mat$y)), function(z) {
    lapply(nu, function(i) {
      suppressMessages(
        suppressWarnings(
          svm(x = merge.mat$x,
              y = as.vector(merge.mat$y[,z]), 
              nu = i, 
              type = 'nu-regression',
              scale = FALSE, 
              kernel = 'linear')
        ))
    })
  }, mc.cores = ncores)
  
  rmse <-  lapply(res, function(z) { 
    lapply(z, function(i){
      sqrt(sum(i$residuals ^ 2)/length(i$residuals))
    })
  })
  rmse <- unlist(lapply(rmse, function(z) which.min(unlist(z))))
  # extract models with min rmse
  mod <- lapply(seq_along(res), function(z) {res[[z]][[rmse[z]]] })
  
  # return coefficients
  coefs <- lapply(mod, function(z) {as.numeric(t(z$coefs) %*% z$SV)})
  coefs <- as.data.frame(t(data.frame(coefs)))
  rownames(coefs) <- colnames(merge.mat$y)
  colnames(coefs) <- colnames(merge.mat$x)
  
  return(coefs)
}


## Read expression data
exp.tpm <- readRDS("data/test_sample.deconvolution.TPM.rds")

## Read APL cell signature 
apl.signature <- read.table("data/CIBERSORTx_sig_1w_branch_mix_out.txt", header = T, row.names = 1)

exp.tpm %>% dim()
exp.tpm %>% head()

decon.bulk <- deconvolution(exp.tpm, apl.signature, 2)

decon.bulk

```

## Regression

``` {r eval = TRUE}

# Read model
linear.model <- readRDS("data/PredModel.rds")

branch.name <- c("Stem_like","CMP_like","S100_GMP_like","GMP_like","Cycling_GMP_like","MDP_like","Bcell","Tcell","Ery_HBB")
pred.score <- NULL
for (i in 1:length(branch.name)) {
  exp = as.matrix(decon.bulk[, i])
  
  lm.model <- linear.model[[i]]
  pred.obv <-  as.numeric(lm.model$coefficients[1]) + 
    as.numeric(lm.model$coefficients[2]) * as.numeric(decon.bulk[, i])
  pred.score <- cbind(pred.score, pred.obv)
}
rownames(pred.score) <- rownames(decon.bulk)
colnames(pred.score) <- branch.name

# Coefficeint matrix
pred.score

pred.percent <- pred.score
for (i in 1:nrow(pred.percent)) {
  if (sum(pred.percent[i, ] < 0) > 0) {
    pred.percent[i, ] <- pred.percent[i, ] - min(pred.percent[i, ]) 
    pred.percent[i, ] <- pred.percent[i, ] / sum(pred.percent[i, ]) * 100
  } else {
    pred.percent[i, ] <- pred.percent[i, ] / sum(pred.percent[i, ]) * 100
  }
}

# Proportion estimation
pred.percent

```

